-- 0021_rezensionen.sql
-- Zweck: Rezensionen als dritter Sachverhalt der Fallstudie — operativ in
--        wawi.rezension (der Shop schreibt sie), analytisch in
--        burgermetrics.fact_reviews (Grain: eine Rezension).
--
--        Ladeweg wie beim Bestand: dataset/fact_reviews.csv ist die Quelle
--        der Wahrheit. lade_csv.py --nur fact_reviews fuellt fact_reviews;
--        dieses Skript kopiert die Simulationszeilen einmalig nach
--        wawi.rezension (Muster 0017). Danach fuehrt der Weg nur noch
--        vorwaerts: Shop -> wawi.rezension -> uebernahme_aus_wawi() ->
--        fact_reviews.
--
--        Rechte werden ausdruecklich gesetzt und nicht ueber Default-
--        Privileges geerbt: GRANT SELECT an studi_daba, anon, authenticated;
--        Row Level Security mit lesen_alle auf beiden Tabellen. Schreiben
--        darf anon nur ueber rezension_anlegen(): Sterne 1-5, Text 5-500
--        Zeichen, hoechstens 20 Rezensionen je Sitzung in zehn Minuten und
--        200 je Stunde insgesamt.
--
-- Aufruf (als postgres):
--   python3 db/skript_ausfuehren.py db/aufbau/0021_rezensionen.sql   -- Tabellen anlegen
--   python3 db/lade_csv.py --nur fact_reviews                        -- CSV laden
--   python3 db/skript_ausfuehren.py db/aufbau/0021_rezensionen.sql   -- Bestand nach wawi kopieren
--   python3 db/materialisieren.py                                    -- neue Sicht materialisieren
--   SELECT * FROM wawi.etl_probe();                                   -- 0 und 0, auch fuer fact_reviews
--
-- Neuladen der CSV nach der Bestandskopie: die Kopie laeuft nur, solange
-- wawi.rezension keine Simulationszeilen hat. Wer fact_reviews.csv neu laedt,
-- entfernt vorher den alten Stand:
--   DELETE FROM wawi.rezension WHERE quelle = 'simulation';
-- und faehrt dieses Skript danach erneut. etl_probe() zeigt jede Abweichung.
--
-- Voraussetzung: 0001-0020 sind gelaufen; als postgres ausfuehren.
-- Objekte: burgermetrics.fact_reviews, burgermetrics.v_rezension_produkt,
--          wawi.rezension, wawi.stg_fact_reviews, wawi.v_rezension_produkt,
--          wawi.v_kundenstimmen, wawi.v_rezension_letzte,
--          wawi.rezension_anlegen(), wawi.uebungsrezensionen_loeschen();
--          neu gefasst: wawi.stg_dim_date, burgermetrics.uebernahme_aus_wawi(),
--          wawi.etl_probe().
-- Ruecknahme: siehe Ende der Datei.
-- Idempotent: ja — die Bestandskopie laeuft nur, wenn wawi.rezension noch
--             keine Simulationszeilen hat.

SET search_path TO wawi, burgermetrics;

-- ---------------------------------------------------------------------------
-- Analytisch: eine Zeile je Rezension. order_id bleibt leer, wenn die
-- Rezension ohne Bestellbezug entstand (Shop ohne Kundenkonto).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS burgermetrics.fact_reviews (
  review_id    bigint PRIMARY KEY,
  date         date NOT NULL REFERENCES burgermetrics.dim_date(date),
  time         time,
  customer_id  bigint REFERENCES burgermetrics.dim_customer(customer_id),
  product_id   bigint NOT NULL REFERENCES burgermetrics.dim_product(product_id),
  branch_id    bigint REFERENCES burgermetrics.dim_branch(branch_id),
  order_id     bigint REFERENCES burgermetrics.fact_orders(order_id) ON DELETE SET NULL,
  stars        smallint NOT NULL CHECK (stars BETWEEN 1 AND 5),
  review_text  text NOT NULL,
  source       text NOT NULL CHECK (source IN ('simulation', 'shop'))
);
CREATE INDEX IF NOT EXISTS ix_bm_reviews_date     ON burgermetrics.fact_reviews(date);
CREATE INDEX IF NOT EXISTS ix_bm_reviews_product  ON burgermetrics.fact_reviews(product_id);
CREATE INDEX IF NOT EXISTS ix_bm_reviews_customer ON burgermetrics.fact_reviews(customer_id);
COMMENT ON TABLE burgermetrics.fact_reviews IS
  'Rezensionen, Grain: eine Rezension. source = simulation (CSV-Bestand) oder shop '
  '(Uebungsrezensionen aus dem Online-Shop, per ETL uebernommen).';

ALTER TABLE burgermetrics.fact_reviews ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS lesen_alle ON burgermetrics.fact_reviews;
CREATE POLICY lesen_alle ON burgermetrics.fact_reviews FOR SELECT USING (true);

-- ---------------------------------------------------------------------------
-- Operativ: die Rezension, wie der Shop sie anlegt. kunde_id und
-- bestellung_id sind optional — der Shop kennt keinen Kunden; der
-- Simulationsbestand traegt beides.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS wawi.rezension (
  rezension_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  artikel_id     bigint NOT NULL REFERENCES wawi.artikel(artikel_id),
  kunde_id       bigint REFERENCES wawi.kunde(kunde_id),
  bestellung_id  bigint REFERENCES wawi.kundenbestellung(bestellung_id) ON DELETE SET NULL,
  filiale_id     bigint REFERENCES wawi.filiale(filiale_id),
  sterne         smallint NOT NULL CHECK (sterne BETWEEN 1 AND 5),
  inhalt         text NOT NULL CHECK (char_length(inhalt) BETWEEN 5 AND 500),
  erstellt_am    timestamptz NOT NULL DEFAULT now(),
  quelle         text NOT NULL CHECK (quelle IN ('simulation', 'shop')),
  sitzung        text
);
CREATE INDEX IF NOT EXISTS ix_wawi_rezension_artikel ON wawi.rezension(artikel_id);
CREATE INDEX IF NOT EXISTS ix_wawi_rezension_kunde   ON wawi.rezension(kunde_id);
CREATE INDEX IF NOT EXISTS ix_wawi_rezension_quelle  ON wawi.rezension(quelle, erstellt_am);
CREATE INDEX IF NOT EXISTS ix_wawi_rezension_sitzung ON wawi.rezension(sitzung, erstellt_am);
COMMENT ON TABLE wawi.rezension IS
  'Rezension eines Artikels. quelle = simulation (aus dem CSV-Bestand kopiert) oder '
  'shop (im Online-Shop geschrieben). Nur der Shop schreibt, ueber rezension_anlegen().';
COMMENT ON COLUMN wawi.rezension.quelle IS
  'simulation = kuratierter Bestand aus fact_reviews.csv; shop = Uebungsrezension aus dem Online-Shop.';

ALTER TABLE wawi.rezension ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS lesen_alle ON wawi.rezension;
CREATE POLICY lesen_alle ON wawi.rezension FOR SELECT USING (true);

-- ---------------------------------------------------------------------------
-- Bestandskopie: die Simulationszeilen einmalig ins operative Schema, mit
-- denselben Kennungen (Muster 0017). Datum und Uhrzeit werden zu einem
-- Zeitstempel in Europe/Berlin; die Uhrzeiten liegen zwischen 07:00 und
-- 23:59, damit die Rueckrechnung in stg_fact_reviews exakt ist.
-- ---------------------------------------------------------------------------
DO $$
DECLARE n bigint;
BEGIN
  SELECT count(*) INTO n FROM wawi.rezension WHERE quelle = 'simulation';
  IF n > 0 THEN
    RAISE NOTICE 'wawi.rezension: Simulationsbestand vorhanden (% Zeilen), nichts zu tun.', n;
    RETURN;
  END IF;
  SELECT count(*) INTO n FROM burgermetrics.fact_reviews WHERE source = 'simulation';
  IF n = 0 THEN
    RAISE NOTICE 'burgermetrics.fact_reviews ist leer — erst lade_csv.py --nur fact_reviews, dann dieses Skript erneut.';
    RETURN;
  END IF;
  INSERT INTO wawi.rezension
        (rezension_id, artikel_id, kunde_id, bestellung_id, filiale_id, sterne, inhalt,
         erstellt_am, quelle, sitzung)
  SELECT r.review_id, r.product_id, r.customer_id, r.order_id, r.branch_id, r.stars, r.review_text,
         (r.date + COALESCE(r.time, TIME '12:00')) AT TIME ZONE 'Europe/Berlin', 'simulation', NULL
  FROM   burgermetrics.fact_reviews r
  WHERE  r.source = 'simulation'
  ORDER  BY r.review_id;
  GET DIAGNOSTICS n = ROW_COUNT;
  RAISE NOTICE 'wawi.rezension: % Rezensionen uebernommen.', n;
  PERFORM setval(pg_get_serial_sequence('wawi.rezension', 'rezension_id'),
                 GREATEST((SELECT max(rezension_id) FROM wawi.rezension), 1));
END $$;

ANALYZE wawi.rezension;
ANALYZE burgermetrics.fact_reviews;

-- ---------------------------------------------------------------------------
-- stg: alle Rezensionen im Auswertungsvokabular, Spaltenfolge wie
-- fact_reviews. Die Probe vergleicht beide Seiten vollstaendig.
-- ---------------------------------------------------------------------------
DROP VIEW IF EXISTS wawi.stg_fact_reviews CASCADE;
CREATE VIEW wawi.stg_fact_reviews AS
SELECT r.rezension_id                                          AS review_id,
       (r.erstellt_am AT TIME ZONE 'Europe/Berlin')::date       AS date,
       date_trunc('second', r.erstellt_am AT TIME ZONE 'Europe/Berlin')::time AS time,
       r.kunde_id                                              AS customer_id,
       r.artikel_id                                            AS product_id,
       r.filiale_id                                            AS branch_id,
       r.bestellung_id                                         AS order_id,
       r.sterne                                                AS stars,
       r.inhalt                                                AS review_text,
       r.quelle                                                AS source
FROM   wawi.rezension r;

-- Zeitdimension: neue Tage koennen jetzt auch aus Rezensionen stammen.
-- Gleiche Spaltenliste wie in 0019, deshalb CREATE OR REPLACE.
CREATE OR REPLACE VIEW wawi.stg_dim_date AS
WITH tage AS (
  SELECT b.bestelldatum AS tag FROM wawi.kundenbestellung b
  UNION
  SELECT (r.erstellt_am AT TIME ZONE 'Europe/Berlin')::date FROM wawi.rezension r
)
SELECT DISTINCT
       to_char(t.tag, 'YYYYMMDD')::bigint        AS date_id,
       t.tag                                    AS date,
       extract(year FROM t.tag)::int            AS year,
       'Q' || extract(quarter FROM t.tag)::int  AS quarter,
       extract(month FROM t.tag)::int           AS month,
       to_char(t.tag, 'FMMonth')                AS month_name,
       extract(week FROM t.tag)::int            AS calendar_week,
       extract(day FROM t.tag)::int             AS day_of_month,
       extract(isodow FROM t.tag)::int          AS day_of_week,
       to_char(t.tag, 'FMDay')                  AS day_name,
       extract(isodow FROM t.tag) >= 6          AS is_weekend,
       false                                    AS is_holiday,
       NULL::text                               AS holiday_name,
       NULL::text                               AS special_event,
       CASE WHEN extract(month FROM t.tag) IN (3, 4, 5)   THEN 'Spring'
            WHEN extract(month FROM t.tag) IN (6, 7, 8)   THEN 'Summer'
            WHEN extract(month FROM t.tag) IN (9, 10, 11) THEN 'Autumn'
            ELSE 'Winter' END                   AS season
FROM   tage t
WHERE  NOT EXISTS (SELECT 1 FROM burgermetrics.dim_date d WHERE d.date = t.tag);

-- ---------------------------------------------------------------------------
-- Sichten fuer den Shop (Phase 3). Alle mit Schema qualifiziert, wie in 0018.
-- ---------------------------------------------------------------------------
DROP VIEW IF EXISTS wawi.v_rezension_produkt CASCADE;
CREATE VIEW wawi.v_rezension_produkt AS
SELECT a.artikel_id,
       a.name,
       count(r.rezension_id)::int                                   AS anzahl,
       round(avg(r.sterne), 1)                                      AS sterne_mittel,
       max((r.erstellt_am AT TIME ZONE 'Europe/Berlin')::date)      AS letzte
FROM   wawi.artikel a
LEFT JOIN wawi.rezension r ON r.artikel_id = a.artikel_id
GROUP  BY a.artikel_id, a.name
ORDER  BY a.artikel_id;
COMMENT ON VIEW wawi.v_rezension_produkt IS
  'Je Artikel: Anzahl und mittlere Sterne aller Rezensionen (Simulation und Shop). '
  'Der Shop zeigt daraus die Bewertung am Produkt.';

-- Nur Simulationstexte: Was Besucher schreiben, erscheint nirgends oeffentlich.
DROP VIEW IF EXISTS wawi.v_kundenstimmen CASCADE;
CREATE VIEW wawi.v_kundenstimmen AS
SELECT s.artikel_id, s.rezension_id, s.sterne, s.inhalt,
       (s.erstellt_am AT TIME ZONE 'Europe/Berlin')::date AS datum
FROM  (SELECT r.*,
              row_number() OVER (PARTITION BY r.artikel_id
                                 ORDER BY r.erstellt_am DESC, r.rezension_id DESC) AS rang
       FROM   wawi.rezension r
       WHERE  r.quelle = 'simulation') s
WHERE  s.rang <= 3
ORDER  BY s.artikel_id, s.rang;
COMMENT ON VIEW wawi.v_kundenstimmen IS
  'Die drei juengsten Rezensionen je Artikel aus dem Simulationsbestand — die einzigen '
  'Texte, die der Shop anzeigt. Besuchertexte (quelle = shop) bleiben ausgeschlossen.';

DROP VIEW IF EXISTS wawi.v_rezension_letzte CASCADE;
CREATE VIEW wawi.v_rezension_letzte AS
SELECT r.rezension_id,
       r.sitzung,
       a.name                              AS artikel,
       f.name                              AS filiale,
       r.sterne,
       r.inhalt,
       r.erstellt_am,
       EXISTS (SELECT 1 FROM burgermetrics.fact_reviews x
               WHERE x.review_id = r.rezension_id) AS im_warehouse
FROM   wawi.rezension r
JOIN   wawi.artikel a ON a.artikel_id = r.artikel_id
LEFT JOIN wawi.filiale f ON f.filiale_id = r.filiale_id
WHERE  r.quelle = 'shop'
ORDER  BY r.erstellt_am DESC
LIMIT  50;
COMMENT ON VIEW wawi.v_rezension_letzte IS
  'Die 50 juengsten Uebungsrezensionen aus dem Shop. im_warehouse sagt, ob der '
  'ETL-Schritt sie schon nach burgermetrics uebernommen hat.';

-- ---------------------------------------------------------------------------
-- Semantikschicht: Bewertung je Produkt. Als Sicht angelegt; materialisieren.py
-- wandelt sie um. Beim zweiten Lauf kann sie schon materialisiert sein, daher
-- die Abfrage der Relationsart (Muster 0018).
-- ---------------------------------------------------------------------------
DO $$
DECLARE r record;
BEGIN
  FOR r IN SELECT c.relkind
           FROM   pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
           WHERE  n.nspname = 'burgermetrics' AND c.relname = 'v_rezension_produkt'
             AND  c.relkind IN ('v', 'm') LOOP
    EXECUTE format('DROP %s IF EXISTS burgermetrics.v_rezension_produkt CASCADE',
                   CASE WHEN r.relkind = 'm' THEN 'MATERIALIZED VIEW' ELSE 'VIEW' END);
  END LOOP;
END $$;
CREATE VIEW burgermetrics.v_rezension_produkt AS
SELECT p.product_id,
       p.product_name,
       p.category,
       count(r.review_id)::int                                                            AS anzahl,
       round(avg(r.stars), 2)                                                             AS sterne_mittel,
       round(100.0 * count(r.review_id) FILTER (WHERE r.stars >= 4) / NULLIF(count(r.review_id), 0), 1) AS anteil_positiv_pct,
       round(100.0 * count(r.review_id) FILTER (WHERE r.stars <= 2) / NULLIF(count(r.review_id), 0), 1) AS anteil_negativ_pct
FROM   burgermetrics.dim_product p
LEFT JOIN burgermetrics.fact_reviews r ON r.product_id = p.product_id
GROUP  BY p.product_id, p.product_name, p.category
ORDER  BY p.product_id;
COMMENT ON VIEW burgermetrics.v_rezension_produkt IS
  'Rezensionen je Produkt: Anzahl, mittlere Sterne, Anteil positiv (4-5) und negativ (1-2). '
  'Kennzahl der Semantikschicht fuer Notebooks, Power BI und Tableau.';

-- ---------------------------------------------------------------------------
-- Schreiben: eine Rezension anlegen. Muster bestellung_anlegen (0018):
-- Parameter heissen wie die Spalten, SECURITY DEFINER, festgenagelter
-- search_path. quelle ist fest 'shop', kunde_id bleibt leer.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION wawi.rezension_anlegen(
  artikel_id  bigint,
  sterne      integer,
  inhalt      text,
  filiale_id  bigint DEFAULT NULL,
  sitzung     text   DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = wawi, pg_temp
AS $$
#variable_conflict use_variable
DECLARE
  v_jetzt     timestamptz := now();
  v_text      text        := btrim(regexp_replace(COALESCE(inhalt, ''), '\s+', ' ', 'g'));
  v_id        bigint;
  v_name      text;
  v_kuerzlich integer;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM artikel a WHERE a.artikel_id = artikel_id) THEN
    RAISE EXCEPTION 'unbekannter Artikel: %', artikel_id USING ERRCODE = '23503';
  END IF;
  IF sterne IS NULL OR sterne < 1 OR sterne > 5 THEN
    RAISE EXCEPTION 'sterne muss zwischen 1 und 5 liegen, nicht %', sterne USING ERRCODE = '22023';
  END IF;
  IF char_length(v_text) < 5 OR char_length(v_text) > 500 THEN
    RAISE EXCEPTION 'der Text braucht 5 bis 500 Zeichen, nicht %', char_length(v_text)
      USING ERRCODE = '22023';
  END IF;
  IF filiale_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM filiale f WHERE f.filiale_id = filiale_id) THEN
    RAISE EXCEPTION 'unbekannte Filiale: %', filiale_id USING ERRCODE = '23503';
  END IF;

  -- Bremse je Sitzung: 20 Rezensionen in zehn Minuten reichen fuer jede Uebung.
  IF sitzung IS NOT NULL THEN
    SELECT count(*) INTO v_kuerzlich
    FROM   rezension r
    WHERE  r.sitzung = sitzung AND r.erstellt_am > v_jetzt - interval '10 minutes';
    IF v_kuerzlich >= 20 THEN
      RAISE EXCEPTION 'zu viele Rezensionen in kurzer Zeit — bitte kurz warten'
        USING ERRCODE = '53400';
    END IF;
  END IF;
  -- Notbremse insgesamt: Der Weg ist oeffentlich; 200 Shop-Rezensionen je
  -- Stunde decken einen ganzen Kurs ab, ein Skript nicht.
  SELECT count(*) INTO v_kuerzlich
  FROM   rezension r
  WHERE  r.quelle = 'shop' AND r.erstellt_am > v_jetzt - interval '1 hour';
  IF v_kuerzlich >= 200 THEN
    RAISE EXCEPTION 'zu viele Rezensionen in der letzten Stunde — bitte spaeter erneut'
      USING ERRCODE = '53400';
  END IF;

  INSERT INTO rezension (artikel_id, kunde_id, bestellung_id, filiale_id, sterne, inhalt,
                         erstellt_am, quelle, sitzung)
  VALUES (artikel_id, NULL, NULL, filiale_id, sterne, v_text, v_jetzt, 'shop', sitzung)
  RETURNING rezension.rezension_id INTO v_id;

  SELECT a.name INTO v_name FROM artikel a WHERE a.artikel_id = artikel_id;
  RETURN jsonb_build_object(
    'rezension_id', v_id,
    'artikel',      v_name,
    'sterne',       sterne,
    'erstellt_am',  v_jetzt,
    'quelle',       'shop');
END $$;
COMMENT ON FUNCTION wawi.rezension_anlegen IS
  'Legt eine Shop-Rezension an: prueft Artikel, Sterne, Textlaenge, Filiale und '
  'bremst Massenanfragen. Einziger Schreibweg fuer anon auf wawi.rezension.';

-- ---------------------------------------------------------------------------
-- ETL neu gefasst: vierte Rueckgabespalte, deshalb DROP + CREATE. Der Rumpf
-- entspricht 0019 plus dem Block fuer die Rezensionen.
-- ---------------------------------------------------------------------------
DROP FUNCTION IF EXISTS burgermetrics.uebernahme_aus_wawi();
CREATE FUNCTION burgermetrics.uebernahme_aus_wawi()
RETURNS TABLE (neue_tage integer, neue_bestellungen integer, neue_positionen integer,
               neue_rezensionen integer)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = burgermetrics, wawi, pg_temp
AS $$
DECLARE
  n_tage integer; n_best integer; n_pos integer; n_rez integer;
BEGIN
  INSERT INTO burgermetrics.dim_date
        (date_id, date, year, quarter, month, month_name, calendar_week, day_of_month,
         day_of_week, day_name, is_weekend, is_holiday, holiday_name, special_event, season)
  SELECT s.date_id, s.date, s.year, s.quarter, s.month, s.month_name, s.calendar_week,
         s.day_of_month, s.day_of_week, s.day_name, s.is_weekend, s.is_holiday,
         s.holiday_name, s.special_event, s.season
  FROM   wawi.stg_dim_date s;
  GET DIAGNOSTICS n_tage = ROW_COUNT;

  INSERT INTO burgermetrics.fact_orders
        (order_id, date, time, hour, branch_id, customer_id, payment_id, promo_id,
         order_channel, item_count, distinct_items, gross_total, discount_amount,
         net_total, order_duration_min, satisfaction_score)
  SELECT s.order_id, s.date, s.time, s.hour, s.branch_id, s.customer_id, s.payment_id,
         s.promo_id, s.order_channel, s.item_count, s.distinct_items, s.gross_total,
         s.discount_amount, s.net_total, s.order_duration_min, s.satisfaction_score
  FROM   wawi.stg_fact_orders s
  WHERE  NOT EXISTS (SELECT 1 FROM burgermetrics.fact_orders o WHERE o.order_id = s.order_id)
  ORDER  BY s.order_id;
  GET DIAGNOSTICS n_best = ROW_COUNT;

  INSERT INTO burgermetrics.fact_order_items
        (order_item_id, order_id, product_id, quantity, unit_price, line_total)
  SELECT s.order_item_id, s.order_id, s.product_id, s.quantity, s.unit_price, s.line_total
  FROM   wawi.stg_fact_order_items s
  WHERE  NOT EXISTS (SELECT 1 FROM burgermetrics.fact_order_items i
                     WHERE i.order_item_id = s.order_item_id)
    AND  EXISTS (SELECT 1 FROM burgermetrics.fact_orders o WHERE o.order_id = s.order_id)
  ORDER  BY s.order_item_id;
  GET DIAGNOSTICS n_pos = ROW_COUNT;

  INSERT INTO burgermetrics.fact_reviews
        (review_id, date, time, customer_id, product_id, branch_id, order_id, stars,
         review_text, source)
  SELECT s.review_id, s.date, s.time, s.customer_id, s.product_id, s.branch_id, s.order_id,
         s.stars, s.review_text, s.source
  FROM   wawi.stg_fact_reviews s
  WHERE  NOT EXISTS (SELECT 1 FROM burgermetrics.fact_reviews r WHERE r.review_id = s.review_id)
  ORDER  BY s.review_id;
  GET DIAGNOSTICS n_rez = ROW_COUNT;

  RETURN QUERY SELECT n_tage, n_best, n_pos, n_rez;
END $$;
COMMENT ON FUNCTION burgermetrics.uebernahme_aus_wawi IS
  'ETL wawi -> burgermetrics: fehlende Kalendertage, Bestellungen, Positionen und '
  'Rezensionen einfuegen. Danach materialisieren.py --neu, sonst zeigt das Dashboard den alten Stand.';

-- Probe: dritte Zeile fuer die Rezensionen, sonst wie 0019.
CREATE OR REPLACE FUNCTION wawi.etl_probe()
RETURNS TABLE (tabelle text, nur_in_wawi bigint, nur_in_burgermetrics bigint)
LANGUAGE sql
SECURITY DEFINER
SET search_path = wawi, burgermetrics, pg_temp
AS $$
  WITH w AS (SELECT order_id, date, hour, branch_id, customer_id, payment_id, promo_id,
                    order_channel, item_count, gross_total, discount_amount, net_total,
                    order_duration_min, satisfaction_score
             FROM wawi.stg_fact_orders),
       b AS (SELECT order_id, date, hour, branch_id, customer_id, payment_id, promo_id,
                    order_channel, item_count, gross_total, discount_amount, net_total,
                    order_duration_min, satisfaction_score
             FROM burgermetrics.fact_orders),
       rw AS (SELECT review_id, date, time, customer_id, product_id, branch_id, order_id,
                     stars, review_text, source
              FROM wawi.stg_fact_reviews),
       rb AS (SELECT review_id, date, time, customer_id, product_id, branch_id, order_id,
                     stars, review_text, source
              FROM burgermetrics.fact_reviews)
  SELECT 'fact_orders'::text,
         (SELECT count(*) FROM (SELECT * FROM w EXCEPT SELECT * FROM b) x),
         (SELECT count(*) FROM (SELECT * FROM b EXCEPT SELECT * FROM w) x)
  UNION ALL
  SELECT 'fact_order_items',
         (SELECT count(*) FROM (SELECT * FROM wawi.stg_fact_order_items
                                EXCEPT SELECT * FROM burgermetrics.fact_order_items) x),
         (SELECT count(*) FROM (SELECT * FROM burgermetrics.fact_order_items
                                EXCEPT SELECT * FROM wawi.stg_fact_order_items) x)
  UNION ALL
  SELECT 'fact_reviews',
         (SELECT count(*) FROM (SELECT * FROM rw EXCEPT SELECT * FROM rb) x),
         (SELECT count(*) FROM (SELECT * FROM rb EXCEPT SELECT * FROM rw) x);
$$;

-- Aufraeumen: Uebungsrezensionen aus beiden Schemata; der Bestand bleibt.
CREATE OR REPLACE FUNCTION wawi.uebungsrezensionen_loeschen()
RETURNS TABLE (aus_burgermetrics integer, aus_wawi integer)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = wawi, burgermetrics, pg_temp
AS $$
DECLARE
  n_bm integer; n_w integer;
BEGIN
  DELETE FROM burgermetrics.fact_reviews r WHERE r.source = 'shop';
  GET DIAGNOSTICS n_bm = ROW_COUNT;
  DELETE FROM wawi.rezension r WHERE r.quelle = 'shop';
  GET DIAGNOSTICS n_w = ROW_COUNT;
  RETURN QUERY SELECT n_bm, n_w;
END $$;

-- ---------------------------------------------------------------------------
-- Rechte, ausdruecklich. Betriebsfunktionen verlieren ihr PUBLIC-EXECUTE
-- (die neu erzeugte uebernahme_aus_wawi haette es sonst wieder).
-- ---------------------------------------------------------------------------
GRANT SELECT ON wawi.rezension, wawi.stg_fact_reviews, wawi.v_rezension_produkt,
                wawi.v_kundenstimmen, wawi.v_rezension_letzte TO anon, authenticated;
GRANT SELECT ON burgermetrics.fact_reviews, burgermetrics.v_rezension_produkt TO anon, authenticated;

REVOKE ALL ON FUNCTION wawi.rezension_anlegen(bigint, integer, text, bigint, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION wawi.rezension_anlegen(bigint, integer, text, bigint, text) TO anon, authenticated;
REVOKE ALL ON FUNCTION burgermetrics.uebernahme_aus_wawi()  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION wawi.etl_probe()                     FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION wawi.uebungsrezensionen_loeschen()   FROM PUBLIC, anon, authenticated;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'studi_daba') THEN
    GRANT SELECT ON wawi.rezension, wawi.stg_fact_reviews, wawi.v_rezension_produkt,
                    wawi.v_kundenstimmen, wawi.v_rezension_letzte TO studi_daba;
    GRANT SELECT ON burgermetrics.fact_reviews, burgermetrics.v_rezension_produkt TO studi_daba;
    REVOKE EXECUTE ON FUNCTION wawi.rezension_anlegen(bigint, integer, text, bigint, text) FROM studi_daba;
  END IF;
END $$;

-- ---------------------------------------------------------------------------
-- Probe: beide Schemata tragen denselben Simulationsbestand; die Rechte sind
-- wie vorgesehen. Bricht mit EXCEPTION ab, wenn nicht.
-- ---------------------------------------------------------------------------
DO $$
DECLARE
  v_sim bigint; v_fr bigint;
  v_fn  text := 'wawi.rezension_anlegen(bigint, integer, text, bigint, text)';
BEGIN
  SELECT count(*) INTO v_sim FROM wawi.rezension WHERE quelle = 'simulation';
  SELECT count(*) INTO v_fr  FROM burgermetrics.fact_reviews WHERE source = 'simulation';
  IF v_sim <> v_fr THEN
    RAISE EXCEPTION 'Simulationsbestand: % Zeilen in wawi, % in burgermetrics', v_sim, v_fr;
  END IF;
  IF NOT has_function_privilege('anon', v_fn, 'EXECUTE') THEN
    RAISE EXCEPTION 'anon darf rezension_anlegen() nicht ausfuehren';
  END IF;
  IF NOT has_table_privilege('anon', 'wawi.v_kundenstimmen', 'SELECT') THEN
    RAISE EXCEPTION 'anon liest v_kundenstimmen nicht';
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'studi_daba') THEN
    IF NOT has_table_privilege('studi_daba', 'wawi.rezension', 'SELECT')
       OR NOT has_table_privilege('studi_daba', 'burgermetrics.fact_reviews', 'SELECT') THEN
      RAISE EXCEPTION 'studi_daba liest die Rezensionen nicht';
    END IF;
    IF has_table_privilege('studi_daba', 'wawi.rezension', 'INSERT')
       OR has_table_privilege('studi_daba', 'burgermetrics.fact_reviews', 'INSERT') THEN
      RAISE EXCEPTION 'studi_daba darf Rezensionen schreiben';
    END IF;
    IF has_function_privilege('studi_daba', v_fn, 'EXECUTE') THEN
      RAISE EXCEPTION 'studi_daba darf rezension_anlegen() ausfuehren';
    END IF;
  END IF;
  RAISE NOTICE 'Rezensionen: % Simulationszeilen in beiden Schemata; Rechte wie vorgesehen.', v_sim;
END $$;

-- Ruecknahme:
--   DROP FUNCTION wawi.uebungsrezensionen_loeschen();
--   DROP FUNCTION wawi.rezension_anlegen(bigint, integer, text, bigint, text);
--   DROP VIEW wawi.v_rezension_letzte, wawi.v_kundenstimmen, wawi.v_rezension_produkt, wawi.stg_fact_reviews;
--   DROP MATERIALIZED VIEW burgermetrics.v_rezension_produkt;   -- oder DROP VIEW vor materialisieren.py
--   DROP TABLE wawi.rezension;
--   DROP TABLE burgermetrics.fact_reviews;
--   uebernahme_aus_wawi(), etl_probe() und stg_dim_date aus 0019 erneut einspielen.
